[phases.setup]
nixPkgs = ['nodejs', 'python3', 'python3Packages.pip']

[phases.install]
cmds = [
    'cd backend && python -m pip install -e ".[dev]"',
    'cd frontend && npm install',
    'cd frontend && npm run build'
]

[phases.build]
cmds = ['cp -r frontend/build backend/static']

[start]
cmd = 'cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT' 